---
adaptive_lighting:
  - name: "Living Room"
    lights:
      - light.living_area_downlights
      - light.stand_lamp
    prefer_rgb_color: false
    transition: 1  # seconds
    initial_transition: 1  # seconds
    interval: 90  # seconds
    min_brightness: 15  # percentage
    max_brightness: 100  # percentage
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1500
    # sunrise_time: "08:00:00"  # override the sunrise time
    # sunrise_offset: '00:00:00'
    # sunset_time:
    # sunset_offset: '00:00:00'  # in seconds or '00:15:00'
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
    separate_turn_on_commands: true
    send_split_delay: 500
    adapt_delay: 1

  - name: "Bedroom"
    lights:
      - light.bed_right
      - light.bed_left
    prefer_rgb_color: false
    transition: 45  # seconds
    initial_transition: 1  # seconds
    interval: 90  # seconds
    min_brightness: 1  # percentage
    max_brightness: 100  # percentage
    min_color_temp: 1000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    # sunrise_time: "08:00:00"  # override the sunrise time
    # sunrise_offset: '00:00:00'
    # sunset_time:
    sunset_offset: '-01:00:00'  # in seconds or '00:15:00'
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false

switch:
  - platform: template
    switches:
      adaptive_lighting:
        value_template: "{{ is_state('switch.adaptive_lighting_living_room', 'on') or is_state('switch.adaptive_lighting_bedroom', 'on') }}"
        turn_on:
          - service: switch.turn_on
            target:
              entity_id: switch.adaptive_lighting_living_room
          - service: switch.turn_on
            target:
              entity_id: switch.adaptive_lighting_bedroom
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.adaptive_lighting_living_room
          - service: switch.turn_off
            target:
              entity_id: switch.adaptive_lighting_bedroom
  - platform: template
    switches:
      adaptive_lighting_sleep_mode:
        value_template: "{{ is_state('switch.adaptive_lighting_sleep_mode_living_room', 'on') or is_state('switch.adaptive_lighting_sleep_mode_bedroom', 'on') }}"
        turn_on:
          - service: switch.turn_on
            target:
              entity_id: switch.adaptive_lighting_sleep_mode_living_room
          - service: switch.turn_on
            target:
              entity_id: switch.adaptive_lighting_sleep_mode_bedroom
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.adaptive_lighting_sleep_mode_living_room
          - service: switch.turn_off
            target:
              entity_id: switch.adaptive_lighting_sleep_mode_bedroom

automation:
  - alias: "Adaptive lighting: reset manual_control after 3 hours"
    mode: parallel
    trigger:
      platform: event
      event_type: adaptive_lighting.manual_control
    variables:
      light: "{{ trigger.event.data.entity_id }}"
      switch: "{{ trigger.event.data.switch }}"
    action:
      - delay: "03:0:00"
      - condition: template
        value_template: "{{ light in state_attr(switch, 'manual_control') }}"
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: "{{ switch }}"
          lights: "{{ light }}"
          manual_control: false
