---
homekit:
  - name: Home Assistant Bridge
    mode: bridge
    port: 51827
    filter:
      include_entities:
        - climate.living_room
        - climate.main_bedroom
        - light.dining_nook_downlights
        - light.living_room_downlights
        - light.entryway_downlights
        - switch.adaptive_lighting_living_room
    entity_config:
      switch.adaptive_lighting_living_room:
        name: Living Room Enable Adaptive Lighting
        type: switch

automation:
  - alias: 'Homekit - Routine Reload'
    trigger:
      - platform: time_pattern
        # This will become seemingly random, as 37 is prime.
        minutes: '/37'
    action:
      - service: homekit.reload
