---
homeassistant:
  name: Home
  unit_system: !secret unit_system
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  customize: !include customize.yaml
  packages: !include_dir_named packages
